name: CI/CD

on:
    push:
        branches:
        - main

jobs:
    deploy:
        name: Deploy DAG to Airflow
        runs-on: ubuntu-latest

        steps:
        - name: Checkout
          uses: actions/checkout@v2
    

        - name: SSH and deploy
          uses: appleboy/ssh-action@v1.0.3
          env:
            SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
            SSH_HOST: ${{ secrets.SSH_HOST }}
            SSH_USERNAME: ${{ secrets.SSH_USERNAME }}

          with:
            host: ${{ secrets.SSH_HOST }}
            username: ${{ secrets.SSH_USERNAME }}
            key: ${{ secrets.SSH_PRIVATE_KEY }}
            script: |
                ls -al
                cd ./airflow/dags
                if [ -d "iart-dags" ]; then
                    cd iart-dags
                    git pull
                else
                    git clone https://github.com/hoangks5/iart-dags.git
            